// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveNotesToDisk(arg1) {
  return window['go']['main']['App']['SaveNotesToDisk'](arg1);
}
